apply plugin: 'com.android.application'

android {
    namespace = 'org.pocketworkstation.pckeyboard'
    compileSdk = 36
    ndkVersion = '28.2.13676358'
    defaultConfig {
        applicationId = 'org.pocketworkstation.pckeyboard.deadkeys'
        minSdk = 21
        targetSdk = 26
        versionCode = 1041001
        versionName = "v1.41.1"
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path = file("CMakeLists.txt")
            version = "3.31.5"
        }
    }
    lint {
        checkReleaseBuilds = false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        //abortOnError = false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation "com.android.support:support-compat:26.0.0"
    testImplementation 'junit:junit:4.13.2'
}
